### PR TITLE
Support for Rails 5

### PR DESCRIPTION
**Pull request by jcoyne**
Also updated the engine_cart stanza

### CODE REVIEW

**Comment by atz** [comment]
This kind of dependency update plus refactor that you might elsewhere complain about being combined in one PR.  It's not that big, but considering it isn't passing CI, breaking it up would help isolate what is failing.

**Comment by jcoyne** [comment]
I'm not exactly sure what you are recommending that I do. All the changes listed here are required for it to run Rails 5.

**Comment by jcoyne** [comment]
This PR depends on https://github.com/projecthydra/hydra-editor/pull/119

**Comment by awead** [comment]
👍

**Pull request merged**
