### PR TITLE
Split option-building from field-building

### PR DESCRIPTION
**Pull request by jechols**
Allows subclasses a bit more flexibility to build HTML fields and/or set options

### CODE REVIEW

**Comment by jechols** [comment]
I wasn't sure how to handle the comment about the index parameter - seems relevant to both functions, but I wasn't sure it made sense to have it twice.  I'll change it / remove it / duplicate it / whatever if that's a concern.

**Comment by jcoyne** [comment]
When I merged this the build broke because it couldn't calculate a valid gemset.

**Comment by jcoyne** [comment]
I think this PR ought to fix the brokenness: https://github.com/projecthydra/hydra-editor/pull/86

**Comment by jechols** [comment]
Odd, sorry about that - I'm sure I ran tests :-/

**Pull request merged**
